/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
plugins {
  id("cpp-application")
}


tasks.register<Exec>("runCpp") { 
    group = "exec"
    description="runs the output from build exe"
    commandLine = listOf("./build/exe/main/debug/${rootProject.name}")
}
